// <auto-generated />
namespace ManageCondo.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class bdv4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bdv4));
        
        string IMigrationMetadata.Id
        {
            get { return "202010300536535_bd-v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
